name: "Max Boll - Web-Developer - Speedcuber - MyXoToD.com"
url: "myxotod.com"
description: "Max Boll, Frontend and Backend Web-Developer from Mayence"
author: "Max Boll"
copyright: "Max Boll"
#rss_path: "/rss"
#rss_name: 
#rss_post_limit: 

markdown: redcarpet
redcarpet:
  extensions: ["strikethrough"]
pygments: true

relative_permalinks: true
permalink:           :title

paginate: 5
paginate_path: "page:num"

# http://blog.nitrous.io/2013/08/30/using-jekyll-plugins-on-github-pages.html