name:     ""
markdown: redcarpet
pygments: true

relative_permalinks: true
permalink:           :title

paginate: 10
paginate_path: "page:num"

# http://blog.nitrous.io/2013/08/30/using-jekyll-plugins-on-github-pages.html